SELECT '--- SELECT VERSION() ---';
SELECT @@version, @@version_comment;

SELECT '--- CREATE DB greatsql, GREATE TABLE t1, INSERT SOME ROWS, SELECT ROWS ---';
SELECT 'CREATE DATABASE IF NOT EXISTS greatsql;' AS EXEC_TEST_SQL;
CREATE DATABASE IF NOT EXISTS greatsql;
SELECT 'USE greatsql;' AS EXEC_TEST_SQL;
USE greatsql;

SELECT 'DROP TABLE IF EXISTS t1;' AS EXEC_TEST_SQL;
DROP TABLE IF EXISTS t1;

SELECT '
CREATE TABLE t1(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
c1 VARCHAR2(30) NOT NULL DEFAULT \'\', 
c2 INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;' AS EXEC_TEST_SQL;
CREATE TABLE t1(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
c1 VARCHAR2(30) NOT NULL DEFAULT '',
c2 INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SELECT 'SHOW CREATE TABLE t1\G' AS EXEC_TEST_SQL;
SHOW CREATE TABLE t1\G

SELECT 'INSERT INTO t1 VALUES 
(0, rand(), ROUND(RAND()*1024000)) ... ' AS EXEC_TEST_SQL;
INSERT INTO t1 VALUES 
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000)),
(0, rand(), ROUND(RAND()*1024000));

INSTALL PLUGIN rapid SONAME 'ha_rapid.so';

SELECT 'ALTER TABLE t1 SECONDARY_ENGINE = rapid;' AS EXEC_TEST_SQL;
ALTER TABLE t1 SECONDARY_ENGINE = rapid;

SELECT 'SHOW CREATE TABLE t1\G' AS EXEC_TEST_SQL;
SHOW CREATE TABLE t1\G

SELECT 'ALTER TABLE t1 SECONDARY_LOAD;' AS EXEC_TEST_SQL;
ALTER TABLE t1 SECONDARY_LOAD;

SELECT "SHOW TABLE STATUS LIKE 't1'\G" AS EXEC_TEST_SQL;
SHOW TABLE STATUS LIKE 't1'\G

SELECT 'SET use_secondary_engine = ON;' AS EXEC_TEST_SQL;
SET use_secondary_engine = ON;

SELECT 'SET secondary_engine_cost_threshold = 0;' AS EXEC_TEST_SQL;
SET secondary_engine_cost_threshold = 0;

SELECT 'EXPLAIN SELECT * FROM t1 WHERE id >= 1;' AS EXEC_TEST_SQL;
EXPLAIN SELECT * FROM t1 WHERE id >= 1;
